// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmYHiFEstJbq3s_uTSutAa3dOKFYKulek',
    appId: '1:627318892443:web:a841d5be00286f1ce9233e',
    messagingSenderId: '627318892443',
    projectId: 'final-project-6f3d8',
    authDomain: 'final-project-6f3d8.firebaseapp.com',
    storageBucket: 'final-project-6f3d8.firebasestorage.app',
    measurementId: 'G-19LZZXK9F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGI7axBom0eBrYFjVAm98CtKTFbivowt4',
    appId: '1:627318892443:android:797e7213f3d2ceade9233e',
    messagingSenderId: '627318892443',
    projectId: 'final-project-6f3d8',
    storageBucket: 'final-project-6f3d8.firebasestorage.app',
  );
}
